version: '3.8'

networks:
  web:
    external: true

services:
  math:
    image: muqimjon/ci-cd
    container_name: "math"
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web
    environment:
      - ASPNETCORE_URLS=http://+:5000
