version: '3'

services:
  math:
    image: muqimjon/ci-cd
    container_name: "math"
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web
      
networks:
  web:
    external: true
